#!/usr/bin/env bash
#
# install all things

[ "${OSTYPE#*darwin}" = "$OSTYPE" ] && is_mac_os=false || is_mac_os=true

export DOTFILES=$(cd "$(dirname "$0")"; pwd -P)
source $DOTFILES/lib/io_handlers.sh

setup_ssh() {
	if [ -f ~/.ssh/id_ed25519.pub ]; then
		log_success 'SSH: Already configured in ~/.ssh/id_rsa.pub'
		return 0
	fi

	if ! $(prompt_confirmation 'SSH: Do you want to configure ssh?'); then
		log_success 'SSH: Skipping ssh configuration'
		return 0
	fi
  
  ssh-keygen -t ed25519
	log_success 'SSH: Configured successfully'
}

# ================================================ #
# ============== Start Installation ============== #
# ================================================ #

log_info '❯❯ Installing dependencies...'
bash $DOTFILES/lib/install_dependencies.sh

# Call installers
array=( $(find -H "$DOTFILES" -maxdepth 3 -name 'install.sh' -not -path '*.git*') )
for installer in ${array[@]}; do
	log_info "❯❯ Installing $installer"
  bash "$installer"
done

log_info "❯❯ Creating Symlinks"
bash $DOTFILES/lib/create_symlinks.sh

setup_ssh

log_success 'All installed!'
